import { User } from './user';

export const USERS: User[] = [
        {
          userName: 'TEST_userName',
          email: 'TEST_email',
          phoneNumber: 'TEST_phoneNumber',
          id: '123456789012345678901234',
          lastName: 'TEST lastName',
          firstName: 'TEST firstName'
          // role: 'Admin',
        },

    // {
    //   name: 'BFY',
    //   city: '123456',
    //   county: 'INGB',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
    // {
    //   name: 'Vodafone',
    //   city: 'Bucuresti',
    //   county: 'Ilfov',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
    // {
    //   name: 'BFY',
    //   city: 'ok',
    //   county: 'INGB',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
    // {
    //   name: 'BFY',
    //   city: '123456',
    //   county: 'INGB',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
    // {
    //   name: 'BFY',
    //   city: '123456',
    //   county: 'INGB',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
    // {
    //   name: 'BFY',
    //   city: '123456',
    //   county: 'INGB',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
    // {
    //   name: 'BFY',
    //   city: '123456',
    //   county: 'INGB',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
    // {
    //   name: 'BFY',
    //   city: '123456',
    //   county: 'INGB',
    //   clientId: '123456789012345678901234',
    //   sal: true,
    //   reg: true ,
    //   vmg: true ,
    //   ail: true ,
    //   asf: true ,
    //   imp: true ,
    //   con: true ,
    // },
  ];
